jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  remotingSecurity:
    enabled: true
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - name: "admin"
          assignments:
            - "chocolateen"
          description: "Marvin master"
          permissions:
            - "Overall/Administer"
        - name: "ape"
          assignments:
            - "i_dont_know"
          description: "Pedagogical team member"
          permissions:
            - "Job/Build"
            - "Job/Read"
            - "Overall/Read"
            - "Job/Workspace"
        - name: "assist"
          assignments:
            - "nasso"
          description: "Assistant"
          permissions:
            - "Job/Read"
            - "Overall/Read"
            - "Job/Workspace"
        - name: "gorilla"
          assignments:
            - "vaugie_g"
          description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
          permissions:
            - "Overall/Read"
            - "Job/Read"
            - "Job/Cancel"
            - "Job/Move"
            - "Job/Build"
            - "Job/Delete"
            - "Job/Create"
            - "Job/Configure"
            - "Job/Workspace"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}
        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}

jobs:
  - file: /var/jenkins_home/job_dsl.groovy